import { Box } from "@mui/material";
import type { Metadata } from "next";
import "./global.css";
import { ReduxProvider } from "@/redux/provider";
import MainScreen from "./MainScreen";

export const metadata: Metadata = {
  title: "netWork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Box
        sx={{
          minHeight: "100vh",
          background: "#819eb0",
          p: "20px 70px 20px 110px",
          overflow: "hidden",
        }}
        component="body"
      >
        <ReduxProvider>
          <MainScreen>{children}</MainScreen>
        </ReduxProvider>
      </Box>
    </html>
  );
}
