version: "3.8"

services:
  backend:
    build: ./backend
    image: backend:sn
    container_name: be-sn_c
    volumes:
      - ./backend/persist:/app/persist
    networks:
      nw:
        ipv4_address: 192.168.0.2
    environment:
      FRONTEND_ADDRESS: "http://192.168.0.3:3000"
    ports:
      - "8888:8888"

  frontend:
    build: ./frontend
    image: frontend:sn
    container_name: fe-sn_c
    ports:
      - "3000:3000"
    networks:
      nw:
        ipv4_address: 192.168.0.3
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://192.168.0.2:8888"

networks:
  nw:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
